mock_login_user=true
server.port=9999
spring.main.allow-bean-definition-overriding=true

spring.thymeleaf.cache=false
spring.thymeleaf.favicon.enabled=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.mvc.static-path-pattern=/
sparrow.ds=druid
